language: android
sudo: required
jdk: oraclejdk8

cache:
  directories:
  - "${TRAVIS_BUILD_DIR}/android/gradle/caches/"
  - "${TRAVIS_BUILD_DIR}/android/gradle/wrapper/dists/"
  - "$HOME/android/.gradle/caches/"
  - "$HOME/android/.gradle/wrapper/"

android:
  components:
    - platform-tools
    - tools
    - build-tools-26.0.2
    - android-26
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

before_script:
  - chmod +x gradlew
  - yes | sdkmanager "platforms;android-26"

script:
  - ./gradlew build
